### ISSUE TITLE
Traceback (most recent call last):   File "/data/data/com.termux/files/home/Zeus-Scanner/zeus.py", line 49, in <module>     reload(sys)     ^^^^^^ NameError: name 'reload' is not defined

### ISSUE THREAD

**Issue by Azarela-Vnk** [Ekultek/Zeus-Scanner#1143]
# What's the problem

# Running context

 - Operating system:
 
 - Zeus version:

# Any idea on a solution?
![Screenshot_20240116_014621_Termux](https://github.com/Ekultek/Zeus-Scanner/assets/84020442/9b4c76d6-c7e0-446e-bea8-be698f345732)

# Full console commands run

# Stacktrace (if applicable)

# Full file log information

**Comment by Ekultek** [comment]
If you use a phone I won't help you

**Comment by Azarela-Vnk** [comment]
Why?

Pada Sel, 16 Jan 2024 01.48, Ekultek ***@***.***> menulis:
