### ISSUE TITLE
cannot run using CentOS

### ISSUE THREAD

**Issue by jmcausing** [Ekultek/Zeus-Scanner#129]
hi there, i cannot seem to run zeus.py. please see below:

[root@localhost zscanner]# ./zeus.py
Traceback (most recent call last):
  File "./zeus.py", line 14, in <module>
    from var import blackwidow
  File "/root/zscanner/var/blackwidow/__init__.py", line 7, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named bs4
[root@localhost zscanner]#

**Comment by Ekultek** [comment]
Run `sudo pip2 install -r requirements.txt` then run `sudo python zeus.py`

**Comment by jmcausing** [comment]
@Ekultek getting this error:

    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=501 -DPSUTIL_LINUX=1 -I/usr/include/python2.7 -c psutil/_psutil_linux.c -o build/temp.linux-x86_64-2.7/psutil/_psutil_linux.o
    psutil/_psutil_linux.c:12:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-KSgEV7/psutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-UFIVbs-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-KSgEV7/psutil/

**Comment by Ekultek** [comment]
[here](https://github.com/Ekultek/Zeus-Scanner#requirements) are the installation instructions and requirements.

What you're going to need to do is this following:
 - `sudo apt-get install libxml2-dev libxslt1-dev python-dev`
 - `sudo pip2 install -r requirements.txt` 
 - `sudo python zeus.py --verbose` 

Post the output, this should work, there's a chance it will fail though.

**Comment by jmcausing** [comment]
@Ekultek I tried that. here is what I did:

1.)  sudo apt-get install libxml2-dev libxslt1-dev python-dev <-- see results below


[root@localhost zscanner]# yum install libxml2-dev libxslt1-dev python-dev
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirrors.nhanhoa.com
 * epel: ftp.riken.jp
 * extras: mirrors.nhanhoa.com
 * updates: mirrors.nhanhoa.com
No package libxml2-dev available.
No package libxslt1-dev available.
No package python-dev available.
Error: Nothing to do

2.)  sudo pip2 install -r requirements.txt <--- this one got errors. please see here: https://pastebin.com/URPGDRst

3.) sudo python zeus.py --verbose <-- error. please see below:

 [root@localhost zscanner]# sudo python zeus.py --verbose
Traceback (most recent call last):
  File "zeus.py", line 14, in <module>
    from var import blackwidow
  File "/root/zscanner/var/blackwidow/__init__.py", line 7, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named bs4

**Comment by jmcausing** [comment]
should I use Ubuntu instead of using CentOS?

**Comment by Ekultek** [comment]
That shouldn't be necessary , the errors you're getting are coming fro, `psutil` so try this:
 - `sudo apt-get install gcc python-devel`
 - `sudo pip2 install -r requirements.txt`

**Comment by jmcausing** [comment]
sudo apt-get install gcc python-devel <-- fixed

sudo pip2 install -r requirements.txt <-- all done.

just another error from running ./zeus.py

[root@localhost zscanner]# ./zeus.py
Traceback (most recent call last):
  File "./zeus.py", line 15, in <module>
    from var.google_search import search
  File "/root/zscanner/var/google_search/search.py", line 18, in <module>
    import google as google_api
ImportError: No module named google

**Comment by Ekultek** [comment]
well now that one is interesting.. give me a couple minutes

**Comment by Ekultek** [comment]
try the following:
`sudo pip2 uninstall google && sudo pip2 install google-api-python-client`

**Comment by jmcausing** [comment]
[root@localhost zscanner]# sudo pip2 uninstall google && sudo pip2 install google-api-python-client
Cannot uninstall requirement google, not installed

**Comment by jmcausing** [comment]
[root@localhost zscanner]# sudo pip2 install google-api-python-client
Requirement already satisfied: google-api-python-client in /usr/lib/python2.7/site-packages
Requirement already satisfied: httplib2<1dev,>=0.9.2 in /usr/lib/python2.7/site-packages (from google-api-python-client)
Requirement already satisfied: oauth2client<5.0.0dev,>=1.5.0 in /usr/lib/python2.7/site-packages (from google-api-python-client)
Requirement already satisfied: uritemplate<4dev,>=3.0.0 in /usr/lib/python2.7/site-packages (from google-api-python-client)
Requirement already satisfied: six<2dev,>=1.6.1 in /usr/lib/python2.7/site-packages (from google-api-python-client)
Requirement already satisfied: pyasn1>=0.1.7 in /usr/lib/python2.7/site-packages (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client)
Requirement already satisfied: pyasn1-modules>=0.0.5 in /usr/lib/python2.7/site-packages (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client)
Requirement already satisfied: rsa>=3.1.4 in /usr/lib/python2.7/site-packages (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client)

**Comment by jmcausing** [comment]
ITS WORKING NOW!! THANK YOU SO!! i tried: sudo pip2 install google

**Comment by Ekultek** [comment]
Lol that'll work also, no problem, have fun

**Comment by Ekultek** [comment]
I edited the README to reflect this issue for centOS and how to install on it https://github.com/Ekultek/Zeus-Scanner/commit/0e3f6fcb731a2782a90aec6e99cff07e4afddb9f
