### ISSUE TITLE
using proxy and google dork search

### ISSUE THREAD

**Issue by jmcausing** [Ekultek/Zeus-Scanner#130]
I am switching from sqlmap to Zeus-Scanner because I can't seem to use sqlmap google dork search with proxy. sqlmap has a switch to use DDN but it does not work.

My question is:

can i still use proxy using google dork search (not DDN) ? most of the time or maybe all the time, when i was using sqlmap, it results such has "detects unusual traffict' which bans the proxy or all of my proxylist.

so can it bypass that issue using zeus-scanner?

**Comment by Ekultek** [comment]
Zeus is capable of using a proxy during the scans. It uses a headless browser to grab the URL so Google thinks you are really a browser. It will also pull the URL from the van URL if you happen to get banned, for manual extraction

**Comment by jmcausing** [comment]
thanks again for answering all of my question.

last question please.

i used --dbs --batch --dbms=mysql using sqlmap.

how can i do that using zeus-scanner?

**Comment by Ekultek** [comment]
It’s going to be a bit of a learning curve, but [here](https://github.com/Ekultek/Zeus-Scanner/wiki/Passing-flags-to-sqlmap) are the instructions with some examples. You’re going to have to use the metavar of the sqlmap args

**Comment by jmcausing** [comment]
got it. thanks again and have a good day.

**Comment by Ekultek** [comment]
You can also run —show-sqlmap to see the sqlmap arguments and —show-nmap to see the nmap arguments

**Comment by Ekultek** [comment]
Also most importantly have fun
