### ISSUE TITLE
Cannot import name ElementNotInteractableException

### ISSUE THREAD

**Issue by qashqao** [Ekultek/Zeus-Scanner#359]
# What's the problem
After a fresh install on Ubuntu 16.04.3 I got the following error : 

Traceback (most recent call last):
  File "zeus.py", line 11, in <module>
    from var.search import selenium_search
  File "/opt/scanners/zeus-scanner/var/search/selenium_search.py", line 18, in <module>
    from selenium.webdriver.remote.errorhandler import (
ImportError: cannot import name ElementNotInteractableException

# Running context
Ubuntu 16.04.3 - Firefox 58.0.2

# Full console commands run
sudo apt-get install libxml2-dev libxslt1-dev python-dev && sudo git clone https://github.com/ekultek/zeus-scanner && cd zeus-scanner && sudo -H pip2 install -r requirements.txt && sudo python zeus.py

![screenshot from 2018-02-21 12-59-11](https://user-images.githubusercontent.com/33896398/36478958-2722886c-1707-11e8-9225-ff07d92b9db4.png)

**Comment by Ekultek** [comment]
If you look at the installation, `pip` didn’t install the correct selenium version for some reason. What you should do is uninstall each library in the requirements file and try again. That should fix the problem

**Comment by Ekultek** [comment]
Been a few days an no answer gonna go ahead and close this
