### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jesuiscamille** [Ekultek/Zeus-Scanner#404]
Hello, I think I'll definitively use [the code you proposed to be used](https://github.com/Ekultek/Zeus-Scanner/blob/master/lib/attacks/sqlmap_scan/__init__.py) in [AutoSQLi](https://github.com/jesuiscamille/AutoSQLi).

Though, legally, I can't because there is no license file in your repository.
Could you add a license please :) ?

Thanks.

**Comment by Ekultek** [comment]
https://github.com/Ekultek/Zeus-Scanner/blob/master/.github/LICENSE.md

Try looking...

**Comment by jesuiscamille** [comment]
One day, my blindness will kill me. Thanks for helping a disabled person.
