### ISSUE TITLE
No module named 'psutil'

### ISSUE THREAD

**Issue by 0m0a1** [Ekultek/Zeus-Scanner#506]
# What's the problem
hello ,my kali installed python psutil
and 
kali:~#python2 zeus.py -h
is OK 

# Running context
but -x will make a error like this:
root@kali:/opt/Zeus-Scanner# python2 zeus.py -x http://XXXXXXXX

    __          __________                             __   
   / /          \____    /____  __ __  ______          \ \  
  / /    ______   /     // __ \|  |  \/  ___/  ______   \ \ 
  \ \   /_____/  /     /\  ___/|  |  /\___ \  /_____/   / / 
   \_\          /_______ \___  >____//____  >          /_/  
                       \/   \/           \/  v1.5.2.910c3e(revision)
	https://github.com/ekultek/zeus-scanner.git
		Advanced Reconnaissance...

[!] legal disclaimer: Usage of Zeus for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program.

[*] starting up at 04:38:25..

[04:38:25 INFO] log file being saved to '/opt/Zeus-Scanner/log/zeus-log-15.log'
[04:38:25 INFO] using default search engine
[04:38:25 CRITICAL] failed to provide a mandatory argument, you will be redirected to the help menu

Traceback (most recent call last):
  File "zeus.py", line 10, in <module>
    from var import blackwidow
  File "/opt/Zeus-Scanner/var/blackwidow/__init__.py", line 6, in <module>
    import lib.core.common
  File "/opt/Zeus-Scanner/lib/core/common.py", line 19, in <module>
    import lib.core.settings
  File "/opt/Zeus-Scanner/lib/core/settings.py", line 21, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
------------------------------------------------
psutil is ok, so can you help me ?

[*] shutting down at 04:38:28..

# Any idea on a solution?

# Full console commands run

# Stacktrace (if applicable)

# Full file log information

**Comment by TheBrownGroupOK** [comment]
pip install -r requirements.txt

**Comment by Ekultek** [comment]
install it
