### ISSUE TITLE
Unsupported Firefox version

### ISSUE THREAD

**Issue by Sydwicked** [Ekultek/Zeus-Scanner#532]
# What's the problem
[13:23:29 CRITICAL] your current firefox version is not supported by Zeus wait..
[*] shutting down at 13:23:29..

# Running context

 - Operating system: Linux kali 4.18.0-kali1-amd64 #1 SMP Debian 4.18.6-1kali1 (2018-09-10) x86_64 GNU/Linux
- Firefox version: 60.2 Oesr (64-bit)
 
 - Zeus version: v1.5.2.910c3e

# Any idea on a solution?

# Full console commands run
 python zeus.py

# Stacktrace (if applicable)
 Successfully installed EasyProcess-0.2.3 lxml-3.7.3 psutil-5.0.1 python-nmap-0.6.1 pyvirtualdisplay-0.2.1 requests-2.12.2 selenium-3.5.0 whichcraft-0.4.1
Attacking targets without consent is not only illegal, but it is unethical and frowned upon in most countries. By installing this program you are agreeing that you are responsible for your own actions, you are over the age of 18 or legally considered an adult in your place of origin, and that you will obey all laws, regulations, and rules set forth by your place of origin. You will only see this disclaimer once. If you agree to the conditions type 'yes'...yes
[13:23:29 CRITICAL] your current firefox version is not supported by Zeus wait..

[*] shutting down at 13:23:29..

# Full file log information

**Comment by Ekultek** [comment]
https://github.com/Ekultek/Zeus-Scanner/blob/master/bin/unzip_gecko.py#L109
