### ISSUE TITLE
No result

### ISSUE THREAD

**Issue by TimV01** [Ekultek/Zeus-Scanner#538]
Please add a option to skip dorks with no results, now it ends the current task instead of skipping them.

**Comment by Ekultek** [comment]
example?

**Comment by TimV01** [comment]
I can't show a example now, I'm installing Parrot OS now instead of Kali.
The Error message was something like this (I don't know the exact message): Query got no results, aborting.

So when there is a dork with no results, please make a option that it doesn't abort the current scan and just ignore that dork and move to the next dork. This is the most usefull when you use a dork list with -l

**Comment by TimV01** [comment]
This is the error message I get when I use a bad dork:

[16:16:17 CRITICAL] did not find any URLs with given query 'filetype:..dk' writing query to blacklist

I can't filter the good dorks so I suggest adding a option that skips the dork instead of abort the task.

@Ekultek
