### ISSUE TITLE
Execution error

### ISSUE THREAD

**Issue by Sydwicked** [Ekultek/Zeus-Scanner#540]
OS: Kali 4.18.0-kali-amd64
Need help please.
root@kali:~/zeus-scanner# python zeus.py 
Traceback (most recent call last):
  File "zeus.py", line 49, in <module>
    reload(sys)
NameError: name 'reload' is not defined

**Comment by Ekultek** [comment]
full commands provided?

**Comment by Ekultek** [comment]
you didnt respond so im closing this

**Comment by sohelahmed786** [comment]
getting same error --
➜  Zeus-Scanner git:(master) python zeus.py   
Traceback (most recent call last):
  File "zeus.py", line 49, in <module>
    reload(sys)
NameError: name 'reload' is not defined
➜  Zeus-Scanner git:(master)
