### ISSUE TITLE
Failed to provide a mandatory argument

### ISSUE THREAD

**Issue by jesp378d** [Ekultek/Zeus-Scanner#541]
# What's the problem

# Running context
 
 - Operating system:Kali linux version 2017.. something...
 
 - Zeus version: v1.5.2.910c3e(

# Any idea on a solution?

# Full console commands run

# Stacktrace (if applicable)

- Failed to provide a mandatory argument

# Full file log information

- 2018-10-16 17:25:30,718;zeus-log;INFO;log file being saved to '/root/Desktop/zeus-scanner/log/zeus-log-10.log'
2018-10-16 17:25:30,719;zeus-log;INFO;using default search engine
2018-10-16 17:25:30,719;zeus-log;CRITICAL;[7;31;31mfailed to provide a mandatory argument, you will be redirected to the help menu

**Comment by Ekultek** [comment]
you didn't provide a mandatory argument whats the problem?

**Comment by jesp378d** [comment]
i'm stupid. Just forget it
