### ISSUE TITLE
Slow getting url's 

### ISSUE THREAD

**Issue by TimVerheul** [Ekultek/Zeus-Scanner#544]
Everything runs fine, but when I get the message: 
no proxy configuration detected
It takes like 2 minutes to scan the second dork, is this normal and if not, how to fix it?

**Comment by Ekultek** [comment]
Yes, it uses selenium, so it has to setup the system before it will start, it can take a few minutes but it helps to bypass google restrictions and bans. Also thank you

**Comment by Ekultek** [comment]
it runs off selenium so it depends on your system and how quick it is to react with the configuration, it also depends a lot on what commands are used, and what you're looking for. so not, not really.
