### ISSUE TITLE
No result (REOPEN)

### ISSUE THREAD

**Issue by TimVerheul** [Ekultek/Zeus-Scanner#551]
This is the error message I get when I use a bad dork:

[16:16:17 CRITICAL] did not find any URLs with given query 'filetype:..dk' writing query to blacklist

I can't filter the good dorks so I suggest adding a option that skips the dork instead of abort the task.

@Ekultek 

P.S. Reopened the Issue since I got the error message.

**Comment by TimV01** [comment]
@Ekultek Take a look at my pull request
